spring:
  profiles:
  datasource:
    platform: postgres
    url: ${WHONEEDS_DB_URL}
    username: ${WHONEEDS_DB_USERNAME}
    password: ${WHONEEDS_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    port: 587
    username: brad@sandbox842a65a256dd4730b4d730492c5965f5.mailgun.org
    password: 9b096bfbaf8651c56a0bb1b712269d73-1553bd45-ee2dc03f
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /whoneeds/api
  port: 9000
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore/whoneeds-api.p12
    key-store-password: changeit
    key-alias: whoneeds-api-keystore
  forward-headers-strategy: native

jwt:
  default:
    expiration: PT2H
  blocklist:
    cleanup:
      delay:
        fixed: 43200000
        initial: 43200000

---
enabled: false
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
