spring:
  profiles:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-34-247-118-233.eu-west-1.compute.amazonaws.com:5432/d7lg8oojfduqgn
    username: rftrsxtjizjtjz
    password: 449578e77c3cd2e5f8d5362dc5a5f6672a466bef2ac3f669adccb3bf9d4e15f5
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: whoneedsKalu@gmail.com
    password: 8A4f5FFDbA47D8AfAaDa7eED64E7aE92D3cB6faFEba74A97d25e55BF4C8Ce86fdbB9A6a67Ce3Aea3E55277afc36afacBfc29
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /whoneeds/api
  port: 9000
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore/whoneeds-api.p12
    key-store-password: changeit
    key-alias: whoneeds-api-keystore
  forward-headers-strategy: native

jwt:
  default:
    expiration: PT2H
  blocklist:
    cleanup:
      delay:
        fixed: 43200000
        initial: 43200000

---

enabled: false
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
